module.exports = {
  SEARCH_COMMON: 'SEARCH_COMMON',
  SEARCH_COMMON_SUCCESS: 'SEARCH_COMMON_SUCCESS',
  SEARCH_COMMON_FAILURE: 'SEARCH_COMMON_FAILURE',
  ERROR_MSG: 'ERROR_MSG',
  VIEW_MORE: 'VIEW_MORE',
  VIEW_MORE_SUCCESS: 'VIEW_MORE_SUCCESS',
  VIEW_MORE_FAILURE: 'VIEW_MORE_FAILURE',
  TARGET_FOLLOWINGS: 'TARGET_FOLLOWINGS',
  TARGET_FOLLOERS: 'TARGET_FOLLOERS'
};
